---
- hosts: testservers
  become_user: root
  become_method: su
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest

    - name: deploy html file
      template:
        src: /tmp/index.html
        dest: /var/www/html/index.html
